### ISSUE TITLE
The embedding matrix of GloVe seems to be damaged

### ISSUE THREAD

**Issue by Flaick** [sibeiyang/sgmn#1]
Thank you for your time!
I recently download the embed_matrix.npy from the link that you offered, and when I load it with **'np.load'**, the error comes out with the information **'ValueError: cannot reshape array of size 19742700 into shape (72704,300)'**.
I checked from the internet and didn't find the relevant solution. The possible one is that the file is damaged so that it can not be loaded correctly. I am wondering if you could help with this or propose another link for that embedding file.
Thank you!

**Comment by sibeiyang** [comment]
@Flaick 

Updated and overwrote the damaged one.

**Comment by Flaick** [comment]
Thanks! That solves my problem!
