### ISSUE TITLE
ModuleInputAttention is not in models.language

### ISSUE THREAD

**Issue by lostnighter** [sibeiyang/sgmn#3]
Hi, Sibei Yang:

Thanks for your great work! When I run    bash experiments/script/train.sh $GPUs, the error below occurs. Maybe you do not upload code for ModuleInputAttention.

Traceback (most recent call last):
  File "./tools/train.py", line 19, in <module>
    from models.scene_graph_reasoning import SGReason
  File "/backup1/home/jlgao/jlgao/controllable/sgmn/tools/../lib/models/scene_graph_reasoning.py", line 5, in <module>
    from models.language import RNNEncoder, ModuleInputAttention
ImportError: cannot import name ModuleInputAttention

Thanks
Junlong

**Comment by sibeiyang** [comment]
Hi Junlong,

Thanks for reminding me. I have updated the code.

Best,
Sibei
